#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace NinjaFactory.DataBase.MySql	
{
	public partial class Ninja_catalogue_item
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _centralID;
		public virtual int CentralID
		{
			get
			{
				return this._centralID;
			}
			set
			{
				this._centralID = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private int? _killCount;
		public virtual int? KillCount
		{
			get
			{
				return this._killCount;
			}
			set
			{
				this._killCount = value;
			}
		}
		
		private string _weapon;
		public virtual string Weapon
		{
			get
			{
				return this._weapon;
			}
			set
			{
				this._weapon = value;
			}
		}
		
		private double? _price;
		public virtual double? Price
		{
			get
			{
				return this._price;
			}
			set
			{
				this._price = value;
			}
		}
		
		private string _speciality;
		public virtual string Speciality
		{
			get
			{
				return this._speciality;
			}
			set
			{
				this._speciality = value;
			}
		}
		
		private int? _jobsCount;
		public virtual int? JobsCount
		{
			get
			{
				return this._jobsCount;
			}
			set
			{
				this._jobsCount = value;
			}
		}
		
		private int? _successfulJobsCount;
		public virtual int? SuccessfulJobsCount
		{
			get
			{
				return this._successfulJobsCount;
			}
			set
			{
				this._successfulJobsCount = value;
			}
		}
		
		private double? _successRate;
		public virtual double? SuccessRate
		{
			get
			{
				return this._successRate;
			}
			set
			{
				this._successRate = value;
			}
		}
		
		private bool? _isDeleted;
		public virtual bool? IsDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				this._isDeleted = value;
			}
		}
		
	}
}
#pragma warning restore 1591
